spring.application.name=payment-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-royal-glade-ad4vcp72-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TM8Yb2RBxCeD
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cybersource HTTP Signature
cybersource.merchant-id=${CYBERSOURCE_MERCHANT_ID:testrest12345_1776252058}
cybersource.merchant-key-id=${CYBERSOURCE_MERCHANT_KEY_ID:802799a5-fa99-4738-b56b-610f463664e5}
cybersource.merchant-secret-key=${CYBERSOURCE_MERCHANT_SECRET_KEY:CK4nq77qbq5/as1LVEiPx6O+4h0mX37EBt3IVUVccFg=}
cybersource.run-environment=${CYBERSOURCE_RUN_ENVIRONMENT:apitest.cybersource.com}

# Origin of the checkout page that hosts the 3DS challenge iframe (postMessage target). Change per environment.
threeds.frontend-origin=http://localhost:63342
